### ISSUE TITLE
ThreatInsight Configuration Continuously Reordering

### ISSUE THREAD

**Issue by Mrorya** [okta/terraform-provider-okta#1221]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 1.1.5
Okta Provider v3.31.0

### Affected Resource(s)

- okta_threat_insight_settings

### Terraform Configuration Files

```hcl
resource "okta_threat_insight_settings" "threat_insight" {
  action = "block"
  network_excludes = [
    okta_network_zone.dummy1.id,
    okta_network_zone.dummy2.id,
    okta_network_zone.dummy3.id,
    okta_network_zone.dummy4.id,
    okta_network_zone.dummy5.id,
    okta_network_zone.dummy6.id,
    okta_network_zone.dummy7.id,
    okta_network_zone.dummy8.id,
    okta_network_zone.dummy9.id
  ]
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

We recently added the threat insight resource to our okta configuration. Since adding this, we've noticed that every single terraform plan has a re-application of the settings where no change is made to the settings except for potentially some reordering of the network zones. These settings had values set prior to adding to terraform, but we did not import the resource before adding as we assumed it would just overwrite (given there's only one threat insight setting per instance).

Ideally, we would only see the threatinsight resource in each successive plan/apply if we added/removed network zones - as is, we see the same set of network_exclusions in every new plan.

### Actual Behavior

Threat insight settings are modified on every plan following addition to TF. Similar to the below (example, not actual output to avoid exposing networkIds):
```
  # okta_threat_insight_settings.threat_insight will be updated in-place
  ~ resource "okta_threat_insight_settings" "threat_insight" {
        id               = "threat_insight_settings"
      ~ network_excludes = [
            "networkid",
          - "networkid",
          - "networkid",
          - "networkid",
          + "networkid",
          + "networkid",
            "networkid",
          + "networkid",
          - "networkid",
        ]
        # (1 unchanged attribute hidden)
    }
```

### Steps to Reproduce

1. Add a bunch of network zone exclusions to threatinsight in the UI
2. Create and apply the threat insight configuration in terraform
3. See reordering of network zones on every future TF plan

### Important Factoids

We are running in OIE, if that matters.

**Comment by monde** [comment]
I suspect the issue is like that fixed in #1171 (use of set vs list in TF SDK). I'll look into it @Mrorya, thanks.

**Comment by monde** [comment]
Thanks @Mrorya, suspect this is a set vs. list bug that I've seen in the provider previously.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-520007

**Comment by Mrorya** [comment]
This is still an issue - should I open a new issue since this was closed out? (I was on PTO during the issue... pruning here)

**Comment by monde** [comment]
not stale

**Comment by Mrorya** [comment]
This is not resolved and should still be addressed - can this be re-opened?

**Comment by monde** [comment]
Released in v3.40.0 https://github.com/okta/terraform-provider-okta/releases/tag/v3.40.0
