### ISSUE TITLE
Can't create multiple okta_policy_rule_signon with explicit priorities 

### ISSUE THREAD

**Issue by pro4tlzz** [okta/terraform-provider-okta#1286]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 1.2.8
registry.terraform.io/okta/okta v3.35.0

### Affected Resource(s)

- okta_policy_signon
- okta_policy_rule_signon
- okta_policy_mfa
- okta_policy_rule_mfa

### Terraform Configuration Files

```hcl
resource "okta_policy_signon" "policy1" {
  name            = "policy1"
  status          = "ACTIVE"
  description     = ""
  groups_included = ["00g4yv4yrmfbnfjnP2MFsjlgjdkd7"]
  priority        = 1
}

resource "okta_policy_rule_signon" "policy1-rule1" {
  depends_on = [
    okta_policy_signon.policy1
  ]
  policy_id           = resource.okta_policy_signon.policy1.id
  name                = "rule1"
  priority            = 1
  status              = "ACTIVE"
  authtype            = "ANY"
  access              = "ALLOW"
  identity_provider   = "ANY"
}

resource "okta_policy_rule_signon" "policy1-rule2" {
  depends_on = [
    okta_policy_signon.policy1
  ]
  policy_id           = resource.okta_policy_signon.policy1.id
  name                = "rule2"
  priority            = 2
  status              = "ACTIVE"
  authtype            = "ANY"
  access              = "ALLOW"
  identity_provider   = "ANY"
}

resource "okta_policy_signon" "policy2" {
  name            = "policy2"
  status          = "ACTIVE"
  description     = ""
  groups_included = ["00g4yv4yrmfbnfjnP2MFsjlgjdkd7"]
  priority        = 2
}

resource "okta_policy_rule_signon" "policy2-rule1" {
  depends_on = [
    okta_policy_signon.policy2
  ]
  policy_id           = resource.okta_policy_signon.policy2.id
  name                = "rule1"
  priority            = 1
  status              = "ACTIVE"
  authtype            = "ANY"
  access              = "ALLOW"
  identity_provider   = "ANY"
}

resource "okta_policy_rule_signon" "policy2-rule2" {
  depends_on = [
    okta_policy_signon.policy2
  ]
  policy_id           = resource.okta_policy_signon.policy2.id
  name                = "rule2"
  priority            = 2
  status              = "ACTIVE"
  authtype            = "ANY"
  access              = "ALLOW"
  identity_provider   = "ANY"
}

resource "okta_policy_signon" "policy3" {
  name            = "policy3"
  status          = "ACTIVE"
  description     = ""
  groups_included = ["00g4yv4yrmfbnfjnP2MFsjlgjdkd7"]
  priority        = 3
}

resource "okta_policy_rule_signon" "policy3-rule1" {
  depends_on = [
    okta_policy_signon.policy3
  ]
  policy_id           = resource.okta_policy_signon.policy3.id
  name                = "rule1"
  priority            = 1
  status              = "ACTIVE"
  authtype            = "ANY"
  access              = "ALLOW"
  identity_provider   = "ANY"
}

resource "okta_policy_rule_signon" "policy3-rule2" {
  depends_on = [
    okta_policy_signon.policy3
  ]
  policy_id           = resource.okta_policy_signon.policy3.id
  name                = "rule2"
  priority            = 2
  status              = "ACTIVE"
  authtype            = "ANY"
  access              = "ALLOW"
  identity_provider   = "ANY"
}
```

### Expected Behavior

What should happen is that Policy1, Policy2 and Policy3 are created. Policy1 has priority of 1, P2 of 2 & P3 of 3.
The rules should also be created with rule1 having priority of 1 and rule2 having priority of 2.

### Actual Behavior

What actually happens is the Okta API for some reason rejects the number i provided for priority and assigns priority 1 to Policy 2 and 1, policy 3 gets priority 2.

Also the Okta API fails to create rule2 for any of the policies and throws up the same fuss about priority.

![image](https://user-images.githubusercontent.com/22709115/188420460-a61349cf-c177-48cb-88f1-88b0c719b73e.png)
The error produced is 

```
╷
│ Error: failed to create sign-on policy rule: failed to create policy rule: the API returned an error: Internal Server Error, x-okta-request-id=YxXFZ-g0ftQAr4T-uEWZrwAABxQ
│ 
│   with module.okta-sign-on-policy.okta_policy_rule_signon.policy1-rule1,
│   on ../modules/sign-on-policies/main.tf line 292, in resource "okta_policy_rule_signon" "policy1-rule1":
│  292: resource "okta_policy_rule_signon" "policy1-rule1" {
│ 
╵
╷
│ Error: failed to create sign-on policy rule: provided priority was not valid, got: 2, API responded with: 1. See schema for attribute details
│ 
│   with module.okta-sign-on-policy.okta_policy_rule_signon.policy1-rule2,
│   on ../modules/sign-on-policies/main.tf line 305, in resource "okta_policy_rule_signon" "policy1-rule2":
│  305: resource "okta_policy_rule_signon" "policy1-rule2" {
│ 
╵
╷
│ Error: failed to create sign-on policy: provided priority was not valid, got: 2, API responded with: 1. See schema for attribute details
│ 
│   with module.okta-sign-on-policy.okta_policy_signon.policy2,
│   on ../modules/sign-on-policies/main.tf line 318, in resource "okta_policy_signon" "policy2":
│  318: resource "okta_policy_signon" "policy2" {
│ 
╵
╷
│ Error: failed to create sign-on policy: provided priority was not valid, got: 3, API responded with: 1. See schema for attribute details
│ 
│   with module.okta-sign-on-policy.okta_policy_signon.policy3,
│   on ../modules/sign-on-policies/main.tf line 352, in resource "okta_policy_signon" "policy3":
│  352: resource "okta_policy_signon" "policy3" {
│ 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by pro4tlzz** [comment]
Updated the main post with more resources that are affected.

I also commented out my rate limit config and I get the same priority errors from the Okta provider.
```hcl
 /* backoff          = true
  min_wait_seconds = 60
  max_wait_seconds = 360
  max_retries      = 6
  request_timeout  = 300
  */
```

Is the provider trying to create everything concurrently?

Because then I would need to add dependencies everywhere

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-531877

**Comment by monde** [comment]
@pro4tlzz I fixed another priority related bug earlier summer. Hopefully that technique will work here as well.

**Comment by pro4tlzz** [comment]
Thank you @monde

**Comment by monde** [comment]
0 value integers were fixed in [v3.44.0](https://github.com/okta/terraform-provider-okta/releases/tag/v3.44.0) release. I'm not sure this issue will benefit from that. @pro4tlzz is this issue still an issue for you?

**Comment by rishigohil** [comment]
It seems this issue still exists - I am trying to create 3 password policies and defined priorities in it but it still gives similar the same error. We are using okta/okta v4.4.3

![image](https://github.com/okta/terraform-provider-okta/assets/5967748/839f9f4c-ea46-4866-80eb-a74655db057e)

**Comment by rishigohil** [comment]
Same issue with `okta_policy_password` resource as well. 

![image](https://github.com/okta/terraform-provider-okta/assets/5967748/a445d27e-9769-40e8-b811-f78ee220d898)

**Comment by pro4tlzz** [comment]
> Same issue with `okta_policy_password` resource as well.
> 
> ![image](https://private-user-images.githubusercontent.com/5967748/334867612-a445d27e-9769-40e8-b811-f78ee220d898.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjMzODIsIm5iZiI6MTcxNzA2MzA4MiwicGF0aCI6Ii81OTY3NzQ4LzMzNDg2NzYxMi1hNDQ1ZDI3ZS05NzY5LTQwZTgtYjgxMS1mNzhlZTIyMGQ4OTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMDk1ODAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTc1MzZlOGMyNjdhOWQ5ZGU5MjAyMzY2ZjNmZDRlMmFhZWM1YmU4NzFkNzZhYzIxZjcwYjlkMTRhMDQ5ZDJmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CLZ6FnSZH6g9xOJTlVHdBr2U2aR8OQmrlcuhWGclPzI)

if you don't use any parallelism and destroy everything and then try again does it work?

**Comment by NMackert** [comment]
Hi everyone, is there an update to this yet? I have the same issue as of now with password policies. Using terraform apply multiple times fixes the issue as it detects the policies being in the wrong order, but it would be nice if it would work ootb. :)
