### ISSUE TITLE
okta_group_role does not recognize role_type of "group_admin"

### ISSUE THREAD

**Issue by pljeskavica** [okta/terraform-provider-okta#1315]
When trying to create a group role so that I can add an administrator role to a group the role "group_admin" is missing from the terraform whitelist.  

```
resource "okta_group_role" "group_admin" {
  group_id = "..."
  role_type = "GROUP_ADMIN"
}
```
Error comes back as:
```
Error: expected value to be one of 'SUPER_ADMIN', 'ORG_ADMIN', 'API_ACCESS_MANAGEMENT_ADMIN', 'APP_ADMIN', 'USER_ADMIN', 'MOBILE_ADMIN', 'READ_ONLY_ADMIN', 'HELP_DESK_ADMIN', 'REPORT_ADMIN', 'GROUP_MEMBERSHIP_ADMIN', got 'GROUP_ADMIN'
```

Group Admin is an important admin role and is a standard okta role.  Listed here in the okta documentation for admin roles: https://help.okta.com/en-us/Content/Topics/Security/administrators-admin-comparison.htm

Currently this means that I have to manually manage that resource in the UI

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

"3.34.0"

### Affected Resource(s)

- okta_group_role

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

I expect terraform to allow me to assign the role "Group Administrator" to a group

### Actual Behavior

```
Error: expected value to be one of 'SUPER_ADMIN', 'ORG_ADMIN', 'API_ACCESS_MANAGEMENT_ADMIN', 'APP_ADMIN', 'USER_ADMIN', 'MOBILE_ADMIN', 'READ_ONLY_ADMIN', 'HELP_DESK_ADMIN', 'REPORT_ADMIN', 'GROUP_MEMBERSHIP_ADMIN', got 'GROUP_ADMIN'
```

### Steps to Reproduce

Assign the role to a group:
```
resource "okta_group_role" "group_admin" {
  group_id = "..."
  role_type = "GROUP_ADMIN"
}
```

1. `terraform apply`

### Important Factoids

I am running version "3.34.0". My Okta tenant was just upgraded to OIE

**Comment by monde** [comment]
Sorry to see this @pljeskavica . Thanks for the documentation reference. I see our public API docs need to be updated as well https://developer.okta.com/docs/reference/api/roles/#role-types

Note to self, code change will be here:
https://github.com/okta/terraform-provider-okta/blob/master/okta/user.go#L179

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-535560

**Comment by monde** [comment]
@pljeskavica it seems like you should be using `GROUP_MEMBERSHIP_ADMIN`. Given the description in the [security docs](https://help.okta.com/en-us/Content/Topics/Security/administrators-admin-comparison.htm) "Permissions to create, add, and remove users apply only to groups that the group admin manages. Group admins can create new users in groups that they manage, remove users from groups that they manage, and move users between groups that they manage."

I looked at the code managing roles in the Okta service and there are only 11 role assignment types defined. I do see that the provider is missing the `CUSTOM` role and I'll do a PR to correct the provider and its documentation.

**Comment by pljeskavica** [comment]
@monde  Please see the User Management Section, from that [link](https://help.okta.com/en-us/Content/Topics/Security/administrators-admin-comparison.htm).  The `GROUP_ADMIN` role has the ability to Create Users, Delete Users, Update Profiles and more.  The `GROUP_MEMBERSHIP_ADMIN` really focusses on adding and removing users from groups.  

the `GROUP_ADMIN` role is very useful for managing admin access to our okta tenant, and the okta docs clearly show that it is a valid standard okta admin role.  The only way I can do this currently is by managing this manually since the terraform project does not support it.

**Comment by monde** [comment]
I'll take a look at this again.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-544453

**Comment by pljeskavica** [comment]
@monde  Can you re open this? Im assuming its not resolved yet.

**Comment by exitcode0** [comment]
No stalebot 🙂

**Comment by CodyKinzett** [comment]
Can we please get this reopened and resolved. having an automated way to add existing group admin roles would be very useful.

**Comment by exitcode0** [comment]
in the `4.0` release okta removed all input validation from the provider, so i'd imagine this bug is now resolved in the `4.*.*` versions?

**Comment by monde** [comment]
@exitcode0 @CodyHR @pljeskavica is this still a bug in v4.x.x ? We removed artificial input validation in the v4.0.0 release. Current version of the provider is v4.5.0. Thanks

**Comment by CodyKinzett** [comment]
our problem was that this list https://help.okta.com/en-us/content/topics/security/administrators-admin-comparison.htm
and this list https://developer.okta.com/docs/reference/api/roles/#role-types are not 1 to 1 because the role type we needed (group_admin) does not appear in the list of role types. Note this is not the same as group_membership_admin. 

if this has been resolved or this is functionality is no longer provided then it can be closed, otherwise this problem appears to still persist.

**Comment by monde** [comment]
Thanks for the reminder @CodyHR , our API docs are going through an upgrade based on an established OpenAPI spec for the Okta Management API and I see that `GROUP_ADMIN` is still missing as a valid type: https://developer.okta.com/docs/api/openapi/okta-management/management/tag/RoleAssignment/#tag/RoleAssignment/operation/assignRoleToUser!path=type&t=request

I'm looking at the actual code in the Okta service and running down a developer that can tell me which role, if any, matches up with what is being described for "Group Admin" in https://help.okta.com/en-us/content/topics/security/administrators-admin-comparison.htm . I'm not seeing `GROUP_ADMIN` in our service code either.

**Comment by monde** [comment]
@exitcode0 @CodyHR @pljeskavica I'm told that `USER_ADMIN` is the role to assign in order to for the user to have the "Group Admin" permissions described in the doc https://help.okta.com/en-us/content/topics/security/administrators-admin-comparison.htm . Also, something historical in the Okta service contributed to this naming mismatch, fwiw. Can you confirm that `USER_ROLE` gets you to the intended result for your situation?

**Comment by CodyKinzett** [comment]
ill forward that on to the relevant parties, ive moved off the project since.

**Comment by monde** [comment]
I'm going to close this is out, given the internal guidance that `USER_ADMIN` is the role to use for the "Group Admin" permission described in the doc https://help.okta.com/en-us/content/topics/security/administrators-admin-comparison.htm . We can re-open if others have new information.
