### ISSUE TITLE
API call exceeded rate limit due to too many requests - TF can not complete due to Okta errors

### ISSUE THREAD

**Issue by ruzickap** [okta/terraform-provider-okta#2166]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash
❯ terraform -v
Terraform v1.5.7
on darwin_arm64
```

### Affected Resource(s)

- all

### Expected Behavior

I would like to create large amount of objectc in Okta using `okta_group`, `okta_group_owner`, `okta_app_group_assignment,` okta_group_owner` resources and read osme data resources like `okta_user`, `okta_app`.

Unfortunately I'm hitting the Okta API limits: `Error returned: Get "https://myorg.okta.com/api/v1/groups/xxxxxxxxxxxx/owners": the API returned an error: API call exceeded rate limit due to too many requests., giving up after 6 attempt(s)`

I tried to set the Okta provider limits parameter to some values but I have never been able to configure it to avoid the Okta API limit errors + TF erros:

```hcl
provider "okta" {
  org_name = "myorg"
  base_url = "okta.com"

  # max_retries      = 10
  # max_wait_seconds = 600
  # min_wait_seconds = 60
  # max_api_capacity = 5
  # max_api_capacity = 1 - terribly slow but doesn't help
  # max_api_capacity = 10

  max_retries      = 30
  backoff          = true
  min_wait_seconds = 60
  max_wait_seconds = 600
}
```

-> Is there any way how I can configure the terraform to put some necessary delays between queries (or anything else) which will allow me to complete the Terraform task?
-> I do not care - how much time (hours) the TF will be running - I need to successfully create the defined objects without errors.

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

### Actual Behavior

Terraform can not complete successfully the change because of the Okta API limits. 

### Steps to Reproduce

1. `terraform apply`

```
│ Error: Error retrieving list group owners
│
│   with okta_group_owner.product_ids_dev2_global_admin["12491"],
│   on okta-dev2.tf line 29, in resource "okta_group_owner" "product_ids_dev2_global_admin":
│   29: resource "okta_group_owner" "product_ids_dev2_global_admin" {
│
│ Error returned: Get "https://myorg.okta.com/api/v1/groups/xxxxxxxxxxxx/owners": the API returned an error: API call exceeded rate limit due to too many requests., giving up after 6 attempt(s)
╵
╷
│ Error: Error retrieving list group owners
│
│   with okta_group_owner.product_ids_dev2_global_admin["17515"],
│   on okta-dev2.tf line 29, in resource "okta_group_owner" "product_ids_dev2_global_admin":
│   29: resource "okta_group_owner" "product_ids_dev2_global_admin" {
│
│ Error returned: Get "https://myorg.okta.com/api/v1/groups/xxxxxxxxxxxx/owners": the API returned an error: API call exceeded rate limit due to too many requests., giving up after 6 attempt(s)
╵
╷
│ Error: Error retrieving list group owners
│
│   with okta_group_owner.product_ids_dev2_global_admin["13218"],
│   on okta-dev2.tf line 29, in resource "okta_group_owner" "product_ids_dev2_global_admin":
│   29: resource "okta_group_owner" "product_ids_dev2_global_admin" {
│
│ Error returned: Get "https://myorg.okta.com/api/v1/groups/xxxxxxxxxxxx/owners": the API returned an error: API call exceeded rate limit due to too many requests., giving up after 6 attempt(s)
╵
```

**Comment by crewbacca2** [comment]
Also seeing this error when we deployed 100 group owner resources in one component.

**Comment by duytiennguyen-okta** [comment]
@ruzickap you can reduce the number of thread with -parallelism=? if you do not care about the run time

**Comment by ruzickap** [comment]
Thank you.
The disadvantage of `-parallelism=?` parameter is, that it will affect the whole terraform "stack" (not only Okta provider) which will really slows down the Terraform execution.

Anyway I guess by [default](https://developer.hashicorp.com/terraform/cli/commands/apply#parallelism-n) the `parallelism` is set to `10`.
I tried `-parallelism=3` and still getting the "API call exceeded rate limit" error.

**Comment by imchrsjms** [comment]
Was facing the same issue with owner assignments as well. 

I had to limit terraform down to half of the api limit (600 to 300) in the provider configuration. I did this because when doing okta_group_owner and okta_group resource operations in the same plan/apply I was hitting the API limit. I suspect that the okta_group_owner call and okta_group may not be treated as the same API endpoint for the self-throttling the Okta provider attempts to do.

**Comment by imchrsjms** [comment]
Keeping alive.

**Comment by imchrsjms** [comment]
@duytiennguyen-okta any chance for a revisit on this? 
We're still facing this issue with api limits on the /groups endpoint while having okta_group and okta_group_owner resources in the same plan causing deployments to fail. Where as just checking okta_group OR okta_group_owner state in Okta doesn't cause the API to hit the limit and, what I understand, waits for the throttle. 

![Image](https://github.com/user-attachments/assets/0a7546de-883e-48ec-af8b-b1757582f7fe)

**Comment by omelnyk1** [comment]
Hello guys,
We also face the same issue. Looks like provider argument `max_api_capacity` does not help here.
In Okta admin page we still can observe the spikes for API endpoints `/ api/v1/groups*`.
